# Generated by Django 3.2 on 2022-11-26 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='addproduct',
            name='notes',
            field=models.CharField(default=1, max_length=100, verbose_name='Notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addproduct',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.CreateModel(
            name='ParcodePrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcode', models.IntegerField(default=0, verbose_name='Parcode')),
                ('product_name', models.CharField(max_length=30, verbose_name='Name')),
                ('quantity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_parcode1', to='products.addquantity', verbose_name='Quantity')),
            ],
        ),
        migrations.AddField(
            model_name='addquantity',
            name='parcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_parcode', to='products.parcodeprint', verbose_name='Parcode'),
        ),
        migrations.AddField(
            model_name='addquantity',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_quantity', to='products.addproduct', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='parcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_parcode', to='products.parcodeprint', verbose_name='Parcode'),
        ),
    ]
