# Generated by Django 3.2 on 2022-12-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='Category/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image'),
        ),
    ]
