# Generated by Django 3.2 on 2022-12-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_storage_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addquantity',
            name='parcode',
        ),
    ]
