# Generated by Django 3.2 on 2022-12-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_addquantity_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquantity',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
    ]
