# Generated by Django 3.2 on 2022-12-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_addquantity_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addquantity',
            name='name',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
    ]
