# Generated by Django 3.2 on 2022-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20221209_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='notes',
            field=models.TextField(default=2, max_length=1000, verbose_name='Notes'),
            preserve_default=False,
        ),
    ]
